import "./board.css";
import "@fortawesome/fontawesome-free/css/all.css"
import "tailwindcss/base";
import "tailwindcss/components";
import "tailwindcss/utilities";
import "./chat_room.scss";
import "./item_table.css";
import "./all_pages.scss";
import "./posts.css"
import "./replies.css"
